# -*- coding: utf-8 -*-
"""AstronomIA_Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpFmDO19XBFaorDjkWFhZ75XS-9SBaDZ

#**Despliegue**

Realizado por: Iván Tang Zhu

Datos: futuro

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción

- Pasos
  - No se pueden pcolocar celdas de texto
  - En este notebook, se ejecuta un despliegue funcional
  - ***No se ejecuta streamlit aqui***
  - Se va streamlit https://streamlit.io/cloud
  - Login con github
  - Se indica repositorio que debe de tener el app.py (este notebook), requirements (para que instale las librerías utilizadas) y el archivo .pkl con los modelos guardados
  - Esto crea un enlace *temporal* con la interfaz gráfica del despliegue. Esto se puede compartir a otros
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Paso 1: Limpiar atípicos
def remove_outliers(X):
    #Se asigna valor nulo a los atípicos

    X.loc[(X["u"] < 0) | (X["u"] >30), "u"] = np.nan
    X.loc[(X["g"] < 0) | (X["g"] >30), "g"] = np.nan
    X.loc[(X["r"] < 0) | (X["r"] >30), "r"] = np.nan
    X.loc[(X["i"] < 0) | (X["i"] >30), "i"] = np.nan
    X.loc[(X["z"] < 0) | (X["z"] >30), "z"] = np.nan


    #Validar todas las variables

    return X

#Cargamos el modelo
import pickle
filename = 'pipeline_modelo.pkl'
pipeline_model, labelencoder = pickle.load(open(filename, 'rb'))
#pipeline_model

#Cargamos los datos futuros
# data = pd.read_csv("datos_futuro.csv")
# data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos
#Recordar: Esto no se ejecuta aqui
import streamlit as st

st.title('Predicción de Objetos Estelares')

u = st.slider('Filtro ultravioleta (u)', min_value=0.0, max_value=30.0, value=20.0, step=0.00001)
g = st.slider('Filtro verde (g)', min_value=0.0, max_value=30.0, value=20.0, step=0.00001)
r = st.slider('Filtro rojo (r)', min_value=0.0, max_value=30.0, value=20.0, step=0.00001)
i = st.slider('Filtro infrarrojo cercano (i)', min_value=0.0, max_value=30.0, value=20.0, step=0.00001)
z = st.slider('Filtro infrarrojo (z)', min_value=0.0, max_value=30.0, value=20.0, step=0.00001)
redshift = st.slider('Corregimiento al rojo', min_value=0.0, max_value=7.0, value=3.0, step=0.00001)

#Dataframe
datos = [[u, g, r, i, z, redshift]]
data = pd.DataFrame(datos, columns=['u', 'g', 'r', 'i', 'z', 'redshift']) #Dataframe con los mismos nombres de variables

"""# **Predicciones**

- Utilizando un Árbol de decisión optimizado con F1 Score del 0,97
"""

#Hacemos la predicción con el Tree
Y_Tree = pipeline_model.predict(data)
print(Y_Tree)

print(labelencoder.inverse_transform(Y_Tree)) # Devuelve a los nombre originales

data['Predicción']=labelencoder.inverse_transform(Y_Tree)
data.head()

data